Updated patch using Rest
ground-context/plugins pull request #1
Opened 2017-04-11 02:31 UTC by ramach

I believe addressed most from last feedback - currently partitions and tables need more work

Database unit test works

2017-04-16 20:29 UTC, akon-dey reviewed
I have taken a first pass of the code changes. I have some logging related nits. Please address them. I will continue to go over the change and provide feedback.

2017-04-16 20:29 UTC, akon-dey commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundStore.java
> +            LOG.debug("Alter database failed with: " + ex.getMessage());
This should be an error.

2017-04-16 20:29 UTC, akon-dey commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundStore.java
> +            LOG.debug("Alter database failed with: {}", ex.getMessage());
This should be an error.

2017-04-16 20:29 UTC, akon-dey commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundTable.java
> +            logger.debug("Not found - Creating table node: " + tableName);
This should be an error log.

2017-04-17 01:23 UTC, ramach commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundTable.java
> +            logger.debug("Not found - Creating table node: " + tableName);
Yes. I will change all these

2017-04-17 19:44 UTC, vsreekanti requested changes
Made a first pass through the code. Things look good for the most part. Code is a lot cleaner than before!

Couple high-level nitpicks: 

* There are a bunch of 10-15 line chunks of code without any line breaks. For readability's sake, please break them up.
* There's a bunch of dead whitespace between methods. Again for readability, please clean up. 😄

2017-04-17 19:44 UTC, vsreekanti commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> + * Licensed to the Apache Software Foundation (ASF) under one
Why is the license formatting changed?

2017-04-17 19:44 UTC, vsreekanti commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundStoreBase.java
> +  public boolean addPartitions(String dbName, String tblName, PartitionSpecProxy partitionSpec, boolean ifNotExists)
Does this fit within the 100 character line limit?

2017-04-17 19:44 UTC, vsreekanti commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundStoreBase.java
> +  public boolean addPartitions(String dbName, String tblName, PartitionSpecProxy partitionSpec, boolean ifNotExists)
True throughout this file.

2017-04-18 16:05 UTC, ramach commented
Will fix. thanks again

On Mon, Apr 17, 2017 at 12:44 PM, Vikram Sreekanti <notifications@github.com
> wrote:

> *@vsreekanti* requested changes on this pull request.
>
> Made a first pass through the code. Things look good for the most part.
> Code is a lot cleaner than before!
>
> Couple high-level nitpicks:
>
>    - There are a bunch of 10-15 line chunks of code without any line
>    breaks. For readability's sake, please break them up.
>    - There's a bunch of dead whitespace between methods. Again for
>    readability, please clean up. 😄
>
> ------------------------------
>
> In hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/
> GroundDatabase.java
> <https://github.com/ground-context/plugins/pull/1#discussion_r111794601>:
>
> > @@ -1,33 +1,31 @@
>  /**
> - * Licensed under the Apache License, Version 2.0 (the "License");
> - * you may not use this file except in compliance with the License.
> - * You may obtain a copy of the License at
> - *
> - *    http://www.apache.org/licenses/LICENSE-2.0
> - *
> + * Licensed to the Apache Software Foundation (ASF) under one
>
> Why is the license formatting changed?
> ------------------------------
>
> In hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/
> GroundStoreBase.java
> <https://github.com/ground-context/plugins/pull/1#discussion_r111803105>:
>
> > @@ -96,37 +69,33 @@ public boolean addPartitions(String dbName, String tblName, List<Partition> part
>      return false;
>    }
>
> -  public boolean addPartitions(String dbName,
> -                               String tblName,
> -                               PartitionSpecProxy partitionSpec,
> -                               boolean ifNotExists)
> +  public boolean addPartitions(String dbName, String tblName, PartitionSpecProxy partitionSpec, boolean ifNotExists)
>
> Does this fit within the 100 character line limit?
> ------------------------------
>
> In hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/
> GroundStoreBase.java
> <https://github.com/ground-context/plugins/pull/1#discussion_r111803225>:
>
> > @@ -96,37 +69,33 @@ public boolean addPartitions(String dbName, String tblName, List<Partition> part
>      return false;
>    }
>
> -  public boolean addPartitions(String dbName,
> -                               String tblName,
> -                               PartitionSpecProxy partitionSpec,
> -                               boolean ifNotExists)
> +  public boolean addPartitions(String dbName, String tblName, PartitionSpecProxy partitionSpec, boolean ifNotExists)
>
> True throughout this file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ground-context/plugins/pull/1#pullrequestreview-33060913>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFcNjEiE5z1BEt32QI1tcOld-sbGSwhGks5rw8EsgaJpZM4M5i46>
> .
>

2017-05-09 15:22 UTC, ramach commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundDatabase.java
> + * Licensed to the Apache Software Foundation (ASF) under one
fixed

2017-05-09 15:24 UTC, ramach commented on hive-plugin/src/main/java/edu/berkeley/ground/plugins/hive/GroundStoreBase.java
> +  public boolean addPartitions(String dbName, String tblName, PartitionSpecProxy partitionSpec, boolean ifNotExists)
We never enforced 100 char limit in the old formatting. I have googlestyle with 100 char limit I can use that. But changes will be too many

2017-05-09 20:49 UTC, vsreekanti approved these changes
This looks great, @ramach! Much cleaner and easier to read.

2017-05-09 20:50 UTC, merged